[package]
name = "ccct"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.18"
rand = "0.8.5"
aes-gcm = "0.9.4"
regex = "1"
hex = "0.4.3"
entropy = "0.4.1"