// arguments
pub const EXIT_EXTRACTING_ARGS_FAILED: i32 = 2;
pub const EXIT_EXTRACTING_ENC_FILE_FAILED: i32 = 3;
pub const EXIT_EXTRACTING_DEC_FILE_FAILED: i32 = 5;
pub const EXIT_EXTRACTING_DEC_KEY_FAILED: i32 = 6;
pub const EXIT_EXTRACTING_INSERT_KEY_FILE_FAILED: i32 = 7;
pub const EXIT_EXTRACTING_INSERT_KEY_KEY_FAILED: i32 = 8;

// encrypt
pub const EXIT_ENCRYPTION_FAILED: i32 = 10;

// decrypt
pub const EXIT_UNHEXLIFYING_KEY_FAILED: i32 = 20;
pub const EXIT_DECRYPTION_FAILED: i32 = 21;

// write_enc_file
pub const EXIT_WRITE_ENC_FILE_FAILED: i32 = 30;

// write_insert_key_file
pub const EXIT_WRITE_INSERT_KEY_FILE_FAILED: i32 = 40;