// arguments
pub const EXIT_EXTRACTING_ARGS_FAILED: i32 = 2;
pub const EXIT_EXTRACTING_ENC_FILE_FAILED: i32 = 3;
pub const EXIT_EXTRACTING_DEC_FILE_FAILED: i32 = 5;
pub const EXIT_EXTRACTING_DEC_KEY_FAILED: i32 = 6;